import type { ThemeDefinition } from './theme.types';

// Cloud Blue — clean white workspace with calm, professional blue accents.
// Light: white page with grey-blue surfaces to separate cards. Dark: layered
// navy surfaces (never pure black) with bright, readable blue accents.
// Fonts use the native OS UI stack: zero-download, zero layout-shift, and a
// naturally clean/professional voice that fits the theme.
const nativeSans =
  'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';

export const cloudBlueTheme: ThemeDefinition = {
  id: 'cloud-blue',
  name: 'Cloud Blue',
  description: 'Clean white workspace with calm blue accents.',
  preview: ['#FFFFFF', '#DBEAFE', '#2563EB', '#0F172A'],
  fontRoles: {
    heading: nativeSans,
    interactive: nativeSans,
    body: nativeSans,
  },
  tokens: {
    light: {
      '--cream': '#F8FAFC',
      '--mint': '#DBEAFE',
      '--teal': '#2563EB',
      '--deep-green': '#0F172A',
      '--brand-cream': '#F8FAFC',
      '--brand-mint': '#DBEAFE',
      '--brand-teal': '#2563EB',
      '--brand-deep': '#0F172A',
      '--color-background': '#FFFFFF',
      '--color-shell': '#F8FAFC',
      '--color-surface': '#FFFFFF',
      '--color-surface-raised': '#F1F5F9',
      '--color-surface-soft': '#EFF6FF',
      '--color-surface-accent': '#DBEAFE',
      '--color-primary': '#2563EB',
      '--color-primary-hover': '#1D4ED8',
      '--color-secondary': '#3B82F6',
      '--color-text': '#0F172A',
      '--color-text-secondary': '#475569',
      '--color-text-muted': '#64748B',
      '--color-border': '#E2E8F0',
      '--color-border-strong': '#CBD5E1',
      '--color-focus': '#2563EB',
      '--color-danger': '#DC2626',
      '--color-warning': '#B45309',
      '--color-progress-track': '#DBEAFE',
      '--color-progress-fill': '#2563EB',
      '--color-focus-progress-track': 'rgba(15, 23, 42, 0.12)',
      '--color-focus-progress-fill': '#2563EB',
      '--color-button-primary-bg': '#2563EB',
      '--color-button-primary-text': '#FFFFFF',
      '--color-button-secondary-bg': '#EFF6FF',
      '--color-button-secondary-text': '#1D4ED8',
      '--color-button-secondary-hover': '#DBEAFE',
      '--color-strong-surface': '#0F172A',
      '--color-on-strong-surface': '#FFFFFF',
      '--color-focus-card': '#DBEAFE',
      '--color-on-focus-card': '#0F172A',
      '--color-quick-card': '#2563EB',
      '--color-on-quick-card': '#FFFFFF',
      '--color-on-primary': '#FFFFFF',
      '--color-on-secondary': '#FFFFFF',
      '--color-nav-bg': '#FFFFFF',
      '--color-nav-active-bg': '#2563EB',
      '--color-nav-active-text': '#FFFFFF',
      '--color-nav-hover': '#EFF6FF',
      '--color-document-surface': '#FFFFFF',
      '--color-document-text': '#0F172A',
      '--color-document-border': '#E2E8F0',
      '--shadow-sm': '0 1px 2px rgba(15, 23, 42, 0.06)',
      '--shadow-md': '0 8px 24px rgba(15, 23, 42, 0.08)',
      '--shadow-document': '0 2px 12px rgba(15, 23, 42, 0.10)',
      '--q-primary': '#2563EB',
      '--q-secondary': '#3B82F6',
      '--q-accent': '#0F172A',
      '--q-dark': '#0F172A',
      '--q-dark-page': '#060B16',
      '--q-positive': '#16A34A',
      '--q-negative': '#DC2626',
      '--q-info': '#2563EB',
      '--q-warning': '#D97706',
      // Extended tokens from the Cloud Blue spec (available for future wiring).
      '--color-primary-soft': '#DBEAFE',
      '--color-accent': '#0F172A',
      '--color-input-bg': '#FFFFFF',
      '--color-input-border': '#CBD5E1',
      '--color-chart-primary': '#2563EB',
      '--color-chart-secondary': '#60A5FA',
      '--color-chart-soft': '#BFDBFE',
    },
    dark: {
      '--cream': '#F8FAFC',
      '--mint': '#DBEAFE',
      '--teal': '#2563EB',
      '--deep-green': '#0F172A',
      '--brand-cream': '#F8FAFC',
      '--brand-mint': '#DBEAFE',
      '--brand-teal': '#2563EB',
      '--brand-deep': '#0F172A',
      '--color-background': '#060B16',
      '--color-shell': '#0B1220',
      '--color-surface': '#111827',
      '--color-surface-raised': '#172033',
      '--color-surface-soft': '#192847',
      '--color-surface-accent': '#192847',
      '--color-primary': '#60A5FA',
      '--color-primary-hover': '#93C5FD',
      '--color-secondary': '#3B82F6',
      '--color-text': '#F8FAFC',
      '--color-text-secondary': '#CBD5E1',
      '--color-text-muted': '#94A3B8',
      '--color-border': 'rgba(148, 163, 184, 0.18)',
      '--color-border-strong': 'rgba(96, 165, 250, 0.32)',
      '--color-focus': '#60A5FA',
      '--color-danger': '#F87171',
      '--color-warning': '#FBBF24',
      '--color-progress-track': '#1E293B',
      '--color-progress-fill': '#60A5FA',
      '--color-focus-progress-track': '#1E293B',
      '--color-focus-progress-fill': '#60A5FA',
      '--color-button-primary-bg': '#60A5FA',
      '--color-button-primary-text': '#07111F',
      '--color-button-secondary-bg': '#192847',
      '--color-button-secondary-text': '#DBEAFE',
      '--color-button-secondary-hover': '#223257',
      '--color-strong-surface': '#172033',
      '--color-on-strong-surface': '#F8FAFC',
      '--color-focus-card': '#172033',
      '--color-on-focus-card': '#F8FAFC',
      '--color-quick-card': '#111827',
      '--color-on-quick-card': '#F8FAFC',
      '--color-on-primary': '#07111F',
      '--color-on-secondary': '#F8FAFC',
      '--color-nav-bg': '#111827',
      '--color-nav-active-bg': '#60A5FA',
      '--color-nav-active-text': '#07111F',
      '--color-nav-hover': '#192847',
      '--color-document-surface': '#172033',
      '--color-document-text': '#F8FAFC',
      '--color-document-border': 'rgba(148, 163, 184, 0.18)',
      '--shadow-sm': '0 1px 2px rgba(0, 0, 0, 0.45)',
      '--shadow-md': '0 8px 24px rgba(0, 0, 0, 0.55)',
      '--shadow-document': '0 2px 12px rgba(0, 0, 0, 0.50)',
      '--q-primary': '#60A5FA',
      '--q-secondary': '#3B82F6',
      '--q-accent': '#DBEAFE',
      '--q-dark': '#0F172A',
      '--q-dark-page': '#060B16',
      '--q-positive': '#4ADE80',
      '--q-negative': '#F87171',
      '--q-info': '#60A5FA',
      '--q-warning': '#FBBF24',
      // Extended tokens from the Cloud Blue spec (available for future wiring).
      '--color-primary-soft': 'rgba(59, 130, 246, 0.18)',
      '--color-accent': '#DBEAFE',
      '--color-input-bg': '#111827',
      '--color-input-border': '#334155',
      '--color-chart-primary': '#60A5FA',
      '--color-chart-secondary': '#3B82F6',
      '--color-chart-soft': '#1E3A5F',
    },
  },
};
