import type { ThemeDefinition } from './theme.types';

// Graphite — the clean "operating system" theme.
// Warm graphite neutrals (paper-and-ink in light, warm charcoal in dark) with a
// single honey-amber accent. Fonts intentionally use the native OS UI stack:
// zero-download, zero layout-shift, and thematically fitting a personal OS dashboard.
const nativeSans =
  'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';

export const graphiteTheme: ThemeDefinition = {
  id: 'graphite',
  name: 'Graphite',
  description: 'Warm graphite neutrals with a honey-amber accent.',
  preview: ['#F2F0E9', '#E4C58C', '#96600C', '#221F19'],
  fontRoles: {
    heading: nativeSans,
    interactive: nativeSans,
    body: nativeSans,
  },
  tokens: {
    light: {
      '--cream': '#F5F3EC',
      '--mint': '#E4C58C',
      '--teal': '#96600C',
      '--deep-green': '#221F19',
      '--brand-cream': '#F5F3EC',
      '--brand-mint': '#E4C58C',
      '--brand-teal': '#96600C',
      '--brand-deep': '#221F19',
      '--color-background': '#ECEAE3',
      '--color-shell': '#F2F0E9',
      '--color-surface': '#F8F6F0',
      '--color-surface-raised': '#FFFFFF',
      '--color-surface-soft': '#E6E3DA',
      '--color-surface-accent': '#DEDACE',
      '--color-primary': '#96600C',
      '--color-primary-hover': '#7C4F08',
      '--color-secondary': '#C79A5A',
      '--color-text': '#221F19',
      '--color-text-secondary': '#4A463D',
      '--color-text-muted': '#726C5E',
      '--color-border': 'rgba(34, 31, 25, 0.14)',
      '--color-border-strong': 'rgba(34, 31, 25, 0.30)',
      '--color-focus': '#96600C',
      '--color-danger': '#C0392B',
      '--color-warning': '#AE4E12',
      '--color-progress-track': '#E2DDD1',
      '--color-progress-fill': '#96600C',
      '--color-focus-progress-track': 'rgba(34, 31, 25, 0.14)',
      '--color-focus-progress-fill': '#221F19',
      '--color-button-primary-bg': '#221F19',
      '--color-button-primary-text': '#F7F4ED',
      '--color-button-secondary-bg': '#EAE5D9',
      '--color-button-secondary-text': '#221F19',
      '--color-button-secondary-hover': '#DFD9CB',
      '--color-strong-surface': '#221F19',
      '--color-on-strong-surface': '#F5F3EC',
      '--color-focus-card': '#EBD9AC',
      '--color-on-focus-card': '#221F19',
      '--color-quick-card': '#96600C',
      '--color-on-quick-card': '#FBF7EE',
      '--color-on-primary': '#FBF7EE',
      '--color-on-secondary': '#221F19',
      '--color-nav-bg': '#F8F6F0',
      '--color-nav-active-bg': '#96600C',
      '--color-nav-active-text': '#FBF7EE',
      '--color-nav-hover': 'rgba(150, 96, 12, 0.10)',
      '--color-document-surface': '#FFFFFF',
      '--color-document-text': '#221F19',
      '--color-document-border': 'rgba(34, 31, 25, 0.10)',
      '--shadow-sm': '0 1px 2px rgba(34, 31, 25, 0.06)',
      '--shadow-md': '0 8px 24px rgba(34, 31, 25, 0.10)',
      '--shadow-document': '0 2px 12px rgba(34, 31, 25, 0.14)',
      '--q-primary': '#221F19',
      '--q-secondary': '#C79A5A',
      '--q-accent': '#96600C',
      '--q-dark': '#221F19',
      '--q-dark-page': '#141310',
      '--q-positive': '#3F7D52',
      '--q-negative': '#C0392B',
      '--q-info': '#96600C',
      '--q-warning': '#AE4E12',
    },
    dark: {
      '--cream': '#F5F3EC',
      '--mint': '#E4C58C',
      '--teal': '#96600C',
      '--deep-green': '#221F19',
      '--brand-cream': '#F5F3EC',
      '--brand-mint': '#E4C58C',
      '--brand-teal': '#96600C',
      '--brand-deep': '#221F19',
      '--color-background': '#141310',
      '--color-shell': '#1B1A15',
      '--color-surface': '#22201A',
      '--color-surface-raised': '#2B2820',
      '--color-surface-soft': '#353128',
      '--color-surface-accent': '#353128',
      '--color-primary': '#E7B45E',
      '--color-primary-hover': '#F1C475',
      '--color-secondary': '#B79364',
      '--color-text': '#F3EFE6',
      '--color-text-secondary': '#CFC9BC',
      '--color-text-muted': '#968F80',
      '--color-border': 'rgba(243, 239, 230, 0.12)',
      '--color-border-strong': 'rgba(231, 180, 94, 0.32)',
      '--color-focus': '#E7B45E',
      '--color-danger': '#F0857B',
      '--color-warning': '#F0A24E',
      '--color-progress-track': '#353128',
      '--color-progress-fill': '#E7B45E',
      '--color-focus-progress-track': '#353128',
      '--color-focus-progress-fill': '#E7B45E',
      '--color-button-primary-bg': '#E7B45E',
      '--color-button-primary-text': '#22201A',
      '--color-button-secondary-bg': '#2B2820',
      '--color-button-secondary-text': '#F3EFE6',
      '--color-button-secondary-hover': '#353128',
      '--color-strong-surface': '#2B2820',
      '--color-on-strong-surface': '#F3EFE6',
      '--color-focus-card': '#3A3324',
      '--color-on-focus-card': '#F3EFE6',
      '--color-quick-card': '#22201A',
      '--color-on-quick-card': '#F3EFE6',
      '--color-on-primary': '#22201A',
      '--color-on-secondary': '#22201A',
      '--color-nav-bg': '#1B1A15',
      '--color-nav-active-bg': '#E7B45E',
      '--color-nav-active-text': '#22201A',
      '--color-nav-hover': '#2B2820',
      '--color-document-surface': '#2B2820',
      '--color-document-text': '#F3EFE6',
      '--color-document-border': 'rgba(243, 239, 230, 0.12)',
      '--shadow-sm': '0 1px 2px rgba(0, 0, 0, 0.40)',
      '--shadow-md': '0 8px 24px rgba(0, 0, 0, 0.50)',
      '--shadow-document': '0 2px 12px rgba(0, 0, 0, 0.45)',
      '--q-primary': '#E7B45E',
      '--q-secondary': '#B79364',
      '--q-accent': '#E7B45E',
      '--q-dark': '#221F19',
      '--q-dark-page': '#141310',
      '--q-positive': '#6FBF8A',
      '--q-negative': '#F0857B',
      '--q-info': '#E7B45E',
      '--q-warning': '#F0A24E',
    },
  },
};
